## Convert python data structures to NumPy array

In [3]:
import numpy as np

print(np.__version__)

1.11.3


In [24]:
my_list = [3, 4,5,7,8]
my_array = np.array(my_list)
my_array

array([3, 4, 5, 7, 8])

In [29]:
my_list * 3
my_array * 3

array([ 9, 12, 15, 21, 24])

In [30]:
my_tuple = (14, 3.5, 7 + 5j)
array = np.array(my_tuple)
array

array([ 14.0+0.j,   3.5+0.j,   7.0+5.j])

## Array creation using arange function

### stop parameter is mandatory for arange

In [31]:
np.arange(4)

array([0, 1, 2, 3])

In [32]:
np.arange(10,30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [33]:
len(np.arange(40,100))

60

In [34]:
np.arange(2,10).size

8

In [35]:
np.arange(10,34,5)

array([10, 15, 20, 25, 30])

## Numy functions linspace() zeros() ones()

### for linspace start and stop parameter are mandatory

### linspace is closed interval while arange is not

In [8]:
np.linspace(5,15,9)

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [9]:
linear_spaced = np.linspace(5,15,9, retstep = True)
linear_spaced

(array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ]),
 1.25)

In [10]:
linear_spaced[1]

1.25

In [12]:
np.zeros(5, dtype= 'int64')

array([0, 0, 0, 0, 0])

In [13]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

## Multi-dimensional arrays

In [ ]:
np.zeros((5,4))

In [ ]:
np.ones((5,4,3))

In [8]:
np.ones(11, dtype='int64')