## Broadcasting => Ability to perform operation between arrays of different sizes

### NumPy requires arrays to be compatible before broadcasting takes place which means arrays must be of equal size or at least one of the sizes is one.

### Smaller array is broadcasted to larger array to perform the operation

In [2]:
import numpy as np

In [3]:
threedarray = np.arange(70)
threedarray.shape = (2,5,7)
threedarray

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69]]])

## Shape, Size, Number Dimension, Data Type

In [4]:
threedarray.shape

(2, 5, 7)

In [5]:
threedarray.ndim

3

In [6]:
threedarray.size

70

In [7]:
threedarray.dtype

dtype('int64')

In [8]:
5 * threedarray + 2

array([[[  2,   7,  12,  17,  22,  27,  32],
        [ 37,  42,  47,  52,  57,  62,  67],
        [ 72,  77,  82,  87,  92,  97, 102],
        [107, 112, 117, 122, 127, 132, 137],
        [142, 147, 152, 157, 162, 167, 172]],

       [[177, 182, 187, 192, 197, 202, 207],
        [212, 217, 222, 227, 232, 237, 242],
        [247, 252, 257, 262, 267, 272, 277],
        [282, 287, 292, 297, 302, 307, 312],
        [317, 322, 327, 332, 337, 342, 347]]])

In [9]:
first_array = np.arange(20).reshape(4,5)

In [10]:
second_array = np.arange(20).reshape(5,4)

In [11]:
#np.inner(first_array,second_array)

#### np.dot => For 2D arrays, it is equivalent to matrix multiplication, and for 1D arrays, to the inner product of vectors

In [12]:
np.dot(first_array,second_array)

array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700],
       [720, 805, 890, 975]])

In [13]:
threedarray

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69]]])

In [14]:
threedarray.sum()

2415

## Broadcasting along the axis

In [15]:
threedarray.sum(axis = 0)

array([[ 35,  37,  39,  41,  43,  45,  47],
       [ 49,  51,  53,  55,  57,  59,  61],
       [ 63,  65,  67,  69,  71,  73,  75],
       [ 77,  79,  81,  83,  85,  87,  89],
       [ 91,  93,  95,  97,  99, 101, 103]])

In [16]:
threedarray.sum(axis = 1)

array([[ 70,  75,  80,  85,  90,  95, 100],
       [245, 250, 255, 260, 265, 270, 275]])

In [17]:
threedarray.sum(axis = 2)

array([[ 21,  70, 119, 168, 217],
       [266, 315, 364, 413, 462]])

### Moral => If you broadcast along axis 0 we emiminate the 0 emelent in shape attribute

In [18]:
threedarray.shape

(2, 5, 7)

## More Example on broadcasting

In [19]:
array1 = np.arange(36).reshape(6,6)

In [20]:
array2 = np.random.random(72).reshape(2,6,6)

In [21]:
result = array1+array2

In [22]:
divider = np.arange(6) + 6

In [23]:
np.set_printoptions(precision = 2)

In [24]:
result/divider

array([[[ 0.13,  0.27,  0.33,  0.43,  0.46,  0.46],
        [ 1.09,  1.12,  1.09,  1.08,  1.07,  1.06],
        [ 2.02,  1.87,  1.85,  1.73,  1.64,  1.61],
        [ 3.1 ,  2.77,  2.51,  2.37,  2.25,  2.15],
        [ 4.14,  3.61,  3.34,  3.1 ,  2.85,  2.7 ],
        [ 5.05,  4.47,  4.09,  3.77,  3.44,  3.19]],

       [[ 0.14,  0.26,  0.37,  0.4 ,  0.44,  0.48],
        [ 1.07,  1.07,  1.11,  1.07,  1.08,  1.05],
        [ 2.05,  1.95,  1.77,  1.68,  1.6 ,  1.56],
        [ 3.15,  2.84,  2.51,  2.43,  2.2 ,  2.14],
        [ 4.13,  3.67,  3.36,  3.11,  2.87,  2.72],
        [ 5.01,  4.53,  4.07,  3.73,  3.49,  3.27]]])

## Structured arrays

In [25]:
data_def = [('Age','i8'),('Name','S6')]

In [26]:
data_def

[('Age', 'i8'), ('Name', 'S6')]

In [27]:
array = np.zeros((4),dtype = data_def)

In [28]:
array

array([(0, b''), (0, b''), (0, b''), (0, b'')], 
      dtype=[('Age', '<i8'), ('Name', 'S6')])

In [29]:
array[3] = (22,'Rabin')

In [30]:
array

array([(0, b''), (0, b''), (0, b''), (22, b'Rabin')], 
      dtype=[('Age', '<i8'), ('Name', 'S6')])

## MultiDimensional structured arrays

In [31]:
multi_array = np.zeros((4,3,3), dtype = data_def)

In [32]:
multi_array

array([[[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]]], 
      dtype=[('Age', '<i8'), ('Name', 'S6')])

In [33]:
multi_array[2,2,2]

(0, b'')

In [34]:
multi_array[2,2,2] = (32,'Jhon')

In [35]:
multi_array

array([[[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (32, b'Jhon')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]]], 
      dtype=[('Age', '<i8'), ('Name', 'S6')])

In [36]:
multi_array['Age']

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0, 32]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [37]:
multi_array[['Age','Name']]

array([[[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (32, b'Jhon')]],

       [[(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')],
        [(0, b''), (0, b''), (0, b'')]]], 
      dtype=[('Age', '<i8'), ('Name', 'S6')])

## Record Array

In [38]:
my_record_array = np.rec.array([(36,'Jackma')],dtype = data_def)
my_record_array

rec.array([(36, b'Jackma')], 
          dtype=[('Age', '<i8'), ('Name', 'S6')])

In [39]:
my_record_array[0].Age

36