# Slicing And Boolean Mask Arrays In NumPy

### Slicing of numpy array means accessing a fragment of the whole array.

## Slicing 1D Arrays

In [2]:
import numpy as np

In [ ]:
our_vector = np.array([-33,-15,0,3,25,100])

In [ ]:
our_vector

In [ ]:
our_vector[0]

In [ ]:
our_vector[0] = -50

In [ ]:
our_vector

In [ ]:
our_vector[-3]

In [ ]:
our_vector[135]

In [ ]:
our_vector[85 % our_vector.size]

# Slicing 2 dimensional arrays

In [ ]:
twodarray = np.arange(40)
twodarray.shape = (8,5)
twodarray

In [ ]:
twodarray[2]

In [ ]:
twodarray[-2]

In [ ]:
twodarray[5,2]

In [ ]:
row = 3
col = 2
twodarray[row,col]

In [ ]:
twodarray[3][3]

# Slicing 3 dimensional arrays

In [ ]:
threedarray = np.arange(24)
threedarray.shape = (4,2,3)
threedarray

In [ ]:
threedarray[1]

In [ ]:
threedarray[1,1]

In [ ]:
threedarray[2,1,2]

In [ ]:
threedarray[2,1,2] = 20

In [ ]:
threedarray

## Boolean Mask Arrays

In [5]:
age_vector = np.array([15,12,34,21,44,16,30])

In [6]:
has_lover = 0 == (age_vector < 20)
has_lover

array([False, False,  True,  True,  True, False,  True], dtype=bool)

In [9]:
ages_has_lover = age_vector[has_lover]
ages_has_lover

array([34, 21, 44, 30])

In [10]:
numbers_array = np.array([-22,33,-4,32,55,-1,0])

In [14]:
positive_test = numbers_array > 0

In [15]:
positive_test

array([False,  True, False,  True,  True, False, False], dtype=bool)

In [16]:
numbers_array[positive_test]

array([33, 32, 55])

### Now what if you want to remove both negative numbers as well as numbers greater than 10

In [19]:
all_numbers = np.array([-10,-6,-3,0,1,23,3,4,5,66,55,78,4])

In [28]:
is_negative = 0 == (all_numbers < 0)
is_negative

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True], dtype=bool)

In [29]:
is_greater_then_ten = 0 == (all_numbers > 10)
is_greater_then_ten

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
       False, False, False,  True], dtype=bool)

In [30]:
final_boolean_mask = np.logical_and(is_negative,is_greater_then_ten)
final_boolean_mask

array([False, False, False,  True,  True, False,  True,  True,  True,
       False, False, False,  True], dtype=bool)

In [31]:
all_numbers[final_boolean_mask]

array([0, 1, 3, 4, 5, 4])