# Slicing And Boolean Mask Arrays In NumPy

### Slicing of numpy array means accessing a fragment of the whole array.

## Slicing 1D Arrays

In [9]:
import numpy as np

In [10]:
our_vector = np.array([-33,-15,0,3,25,100])

In [11]:
our_vector

array([-33, -15,   0,   3,  25, 100])

In [12]:
our_vector[0]

-33

In [13]:
our_vector[0] = -50

In [14]:
our_vector

array([-50, -15,   0,   3,  25, 100])

In [15]:
our_vector[-3]

3

In [16]:
#our_vector[135]

In [17]:
our_vector[85 % our_vector.size]

-15

# Slicing 2 dimensional arrays

In [18]:
twodarray = np.arange(40)
twodarray.shape = (8,5)
twodarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [19]:
twodarray[2]

array([10, 11, 12, 13, 14])

In [20]:
twodarray[-2]

array([30, 31, 32, 33, 34])

In [21]:
twodarray[5,2]

27

In [22]:
row = 3
col = 2
twodarray[row,col]

17

In [23]:
twodarray[3][3]

18

# Slicing 3 dimensional arrays

In [24]:
threedarray = np.arange(24)
threedarray.shape = (4,2,3)
threedarray

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [25]:
threedarray[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
threedarray[1,1]

array([ 9, 10, 11])

In [27]:
threedarray[2,1,2]

17

In [28]:
threedarray[2,1,2] = 20

In [29]:
threedarray

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 20]],

       [[18, 19, 20],
        [21, 22, 23]]])

## Boolean Mask Arrays

In [30]:
age_vector = np.array([15,12,34,21,44,16,30])

In [31]:
has_lover = 0 == (age_vector < 20)
has_lover

array([False, False,  True,  True,  True, False,  True], dtype=bool)

In [32]:
ages_has_lover = age_vector[has_lover]
ages_has_lover

array([34, 21, 44, 30])

In [33]:
numbers_array = np.array([-22,33,-4,32,55,-1,0])

In [34]:
positive_test = numbers_array > 0

In [35]:
positive_test

array([False,  True, False,  True,  True, False, False], dtype=bool)

In [36]:
numbers_array[positive_test]

array([33, 32, 55])

### Now what if you want to remove both negative numbers as well as numbers greater than 10

In [37]:
all_numbers = np.array([-10,-6,-3,0,1,23,3,4,5,66,55,78,4])

In [38]:
is_negative = 0 == (all_numbers < 0)
is_negative

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True], dtype=bool)

In [39]:
is_greater_then_ten = 0 == (all_numbers > 10)
is_greater_then_ten

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
       False, False, False,  True], dtype=bool)

In [40]:
final_boolean_mask = np.logical_and(is_negative,is_greater_then_ten)
final_boolean_mask

array([False, False, False,  True,  True, False,  True,  True,  True,
       False, False, False,  True], dtype=bool)

In [41]:
all_numbers[final_boolean_mask]

array([0, 1, 3, 4, 5, 4])